export const SignUP = "SignUp/Register";
export const UserList = "User/UserList";
export const UserListWithRole = "User/UserListWithRole";
export const DeleteUserByUserId = "User/DeleteUserByUserId";
export const DELETEUSERBYNAME = "User/DeleteUserByUsername"
export const LOGIN = "User/ValidateUser";
export const USERLOCKUNLOCK = "User/LockUnlockUser";
export const RESETPASSWORD = "User/ResetPassword";
export const USER_FORGOT_PASSWORD = "User/ForgotPassword";
export const USER_PASSWORD_CHANGE = "User/ChangePassword";
export const LOGOUT = "User/Logout";
export const CREATE_REGISTRATION = "Registration/CreateRegistration";
export const Gender_List = "Master/GenderDropdown";
export const Payment_Type_List = "Master/PaymentTypeList";
export const Relationship_List = "Master/RelationshipDropdown";
export const State_List = "Master/StateDropdown";
export const UserRole_List = "Master/UserRoleList";
export const School_Grade_List = "Master/SchoolGradeDropdown";
export const Registered_Student_List = "Registration/RegisteredStudentList";
export const USERANDROLEDETAILS = "User/UserAndRoleDetails";
export const Address_Type_List = "Master/AddressTypeList";
export const ACADEMICYEAR = "AcademicYear/GetAcademicYears";
export const GetDDL = "Master/GetData";
export const SCHEDULEVIEW = "PathshalaSchedule/GetPathshalaScheduleByAcademicYearId";
export const CURRENTYEAR = "AcademicYear/GetCurrentAcademicYear"
export const PAYMENTHISTORY = "Payment/GetPaymentHistoryByUserId";
export const MEMBERWISEPAYMENTLIST = "Payment/MemberwisePaymentList";
export const Get_ParentList_By_StudentId = "Registration/GetParentListByStudentId";
export const Get_RegisteredStudentList_By_UserID = "Registration/GetRegisteredStudentListByUserID";
export const Get_Payment_Allocation = "Payment/GetPaymentAllocation";
export const Add_Payment_Allocation = "Payment/AddPaymentAllocation";
export const GETGATHADETAILSPERSTUDENT ="Student/StudentGathaProgressDetail"
export const NEWSTUDENTLIST ="Registration/NewStudentList"
export const PARENTLISTBYMEMBERID ="Registration/GetParentListByMemberId"
